apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
spec:
  selector:
    app: calculator-app
  ports:
    - protocol: TCP
      port: 80  # Service port (can be any port you want to expose externally)
      targetPort: 3040  # Port your Node.js app listens on inside the pod
  type: LoadBalancer  # Expose the service externally
